---
- name: apt install webmin dependencies
  become: yes
  apt:
    state: present
    name: [
      'perl',
      'python',
      'openssl',
      'libnet-ssleay-perl',
      'libauthen-pam-perl',
      'libpam-runtime',
      'libio-pty-perl',
      'apt-show-versions'
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed
- name: apt install webmin
  become: yes
  apt:
    deb: /usr/local/src/{{ webmin_name }}
    state: present