- name: check theme exists
  stat:
    path: "{{ webmin_source[ansible_os_family].install_dir}}{{ item.name }}"
  register: webmin_theme_check
- name: download theme
  become: yes
  unarchive:
    dest: "{{ webmin_source[ansible_os_family].install_dir}}"
    src: "{{ item.url }}"
    owner: root
    group: root
    remote_src: yes
  register: webmin_theme_download
  retries: 3
  delay: 10
  until: not webmin_theme_download.failed
  when: not webmin_theme_check.stat.exists