---
- name: yum install webmin dependencies
  become: yes
  yum:
    name: perl-Net-SSLeay
    state: present
    update_cache: true
- name: yum install webmin
  become: yes
  yum:
    name: /usr/local/src/{{ webmin_name }}
    state: present